[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "queues"
version = "0.1.0"
description = "A queue management library for CloudSeeder2"
authors = [{ name = "GroGBot", email = "grogbot@robotlab-x.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "boto3",
    "azure-servicebus",
    "azure-storage-queue"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
queues = ["*.json"] 

[project.optional-dependencies]
dev = ["pytest", "black", "mypy"]
