[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "database"
version = "0.1.0"
description = "A database library for managing data in CloudSeeder"
authors = [{ name = "GroGBot", email = "grogbot@robotlab-x.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "tinydb",  # Add other dependencies here if needed
]

[tool.setuptools]
packages = ["database"]

[tool.setuptools.package-data]
database = ["*.json"]  # Adjust if you have data files

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = ["pytest", "black", "mypy"]  # Development dependencies
