[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "auth"
version = "0.1.0"
description = "A Python library for auth"
authors = [{ name = "Your Name", email = "your@email.com" }]
requires-python = ">=3.10"

dependencies = [
    "boto3",
    "jwt"
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]